######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 31 17:14:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/sameVolume.h
SOURCES += src/main.cpp src/sameVolume.cpp
QT += 
DEFINES += DEBUG
